POST http://localhost:8082/user/register
Content-Type: application/json

{
    "fullname": "Shubham Pandey",
    "username": "deltadev",
    "email": "pandeyxvii.com",
    "password": ""
}

###
Get http://localhost:8082/user/all
X-Auth: x-Header_key

###
POST http://localhost:8082/discussion/new
Content-Type: application/json

{
    "title": "Topic_12",
    "author": "deltadev2",
    "content": "Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..."
}

###
GET http://localhost:8082/discussion/all1
x-api-key : abracadabra