POST http://localhost:8082/user/register
Content-Type: application/json

{
    "fullName": "Yuvraj Singh",
    "username": "yuvipaji",
    "email": "yuvi@india.com",
    "birthdate": "14-07-2006",
    "password": "yuvi6sixes@t20cwc2007"
}